- alias: beo
  id: beoscript
  hide_entity: true
  trigger:
  - platform: state
    entity_id: input_select.beo_mode
  action:
  - service: script.beo_source
- id: beo radio mqtt
  alias: beo_radio
  trigger:
  - platform: mqtt
    topic: beo/src1
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.beo_mode
      option: >
        {% if trigger.payload == 'radio' %}
              Radio
        {% elif trigger.payload == 'tape' %}
              Tape
        {% elif trigger.payload == 'aux' %}
              Auxiliary
        {% endif %}



- alias: bedroomswitch
  id: bedroomstart
  trigger:
  - platform: state
    entity_id: sensor.bedroom_open_window
    to: 'True'
  action:
  - service: timer.start
    entity_id: timer.bedroom
- alias: Bedroom stop
  id: bedroomstop
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bedroom
  action:
  - service: notify.mobile_app_TomXR
    data:
      message: Close bedroom windows
- alias: Stop bedroom timer
  id: stopbedroomtimer
  trigger:
  - platform: state
    entity_id: sensor.bedroom_open_window
    to: 'False'
  action:
  - service: timer.cancel
    entity_id: timer.bedroom
- alias: guestswitch
  id: gueststart
  trigger:
  - platform: state
    entity_id: sensor.guest_room_open_window
    to: 'True'
  action:
  - service: timer.start
    entity_id: timer.guestroom
- alias: Guest stop
  id: gueststop
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.guestroom
  action:
  - service: notify.mobile_app_TomXR
    data:
      message: Close guest room windows
- alias: Stop guestroom timer
  id: stopguestroomtimer
  trigger:
  - platform: state
    entity_id: sensor.guest_room_open_window
    to: 'False'
  action:
  - service: timer.cancel
    entity_id: timer.guestroom
- alias: livingswitch
  id: livingstart
  trigger:
  - platform: state
    entity_id: sensor.living_room_open_window
    to: 'True'
  action:
  - service: timer.start
    entity_id: timer.livingroom
- alias: Living stop
  id: livingstop
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.livingroom
  action:
  - service: notify.mobile_app_TomXR
    data:
      message: Close living room windows
- alias: Stop livingroom timer
  id: stoplivingroomtimer
  trigger:
  - platform: state
    entity_id: sensor.living_room_open_window
    to: 'False'
  action:
  - service: timer.cancel
    entity_id: timer.livingroom
- alias: diningswitch
  id: diningstart
  trigger:
  - platform: state
    entity_id: sensor.spisestue_open_window
    to: 'True'
  action:
  - service: timer.start
    entity_id: timer.diningroom
- alias: dining stop
  id: diningstop
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.diningroom
  action:
  - service: notify.mobile_app_TomXR
    data:
      message: Close dining room windows
- alias: Stop diningroom timer
  id: stopdiningroomtimer
  trigger:
  - platform: state
    entity_id: sensor.spisestue_open_window
    to: 'False'
  action:
  - service: timer.cancel
    entity_id: timer.diningroom
- alias: kitchenswitch
  id: kitchenstart
  trigger:
  - platform: state
    entity_id: sensor.kitchen_open_window
    to: 'True'
  action:
  - service: timer.start
    entity_id: timer.kitchen
- alias: kitchen stop
  id: kitchenstop
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.kitchen
  action:
  - service: notify.mobile_app_TomXR
    data:
      message: Close kitchen window
- alias: Stop kitchen timer
  id: stopkitchentimer
  trigger:
  - platform: state
    entity_id: sensor.kitchen_open_window
    to: 'False'
  action:
  - service: timer.cancel
    entity_id: timer.kitchen
- alias: bathroomswitch
  id: bathroomstart
  trigger:
  - platform: state
    entity_id: sensor.bathroom_open_window
    to: 'True'
  action:
  - service: timer.start
    entity_id: timer.bathroom
- alias: bathroom stop
  id: bathroomstop
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bathroom
  action:
  - service: notify.mobile_app_TomXR
    data:
      message: Close bathroom window
- alias: Stop bathroom timer
  id: stopbathroomtimer
  trigger:
  - platform: state
    entity_id: sensor.bathroom_open_window
    to: 'False'
  action:
  - service: timer.cancel
    entity_id: timer.bathroom
