- alias: beo
  id: beoscript
  hide_entity: true
  trigger:
  - platform: state
    entity_id: input_select.beo_mode
  action:
  - service: script.beo_source
- id: beo radio mqtt
  alias: beo_radio
  trigger:
  - platform: mqtt
    topic: beo/src1
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.beo_mode
      option: >
        {% if trigger.payload == 'radio' %}
              Radio
        {% elif trigger.payload == 'tape' %}
              Tape
        {% elif trigger.payload == 'aux' %}
              Auxiliary
        {% endif %}

